"""Deterministic, approval-bound RouterOS runbooks."""

from mth.core.runbooks.base import (
    RunbookApplyResult,
    RunbookBackend,
    RunbookDefinition,
    RunbookError,
    RunbookExecutor,
    RunbookField,
    RunbookFieldKind,
    RunbookPlan,
    RunbookRollbackPreview,
    RunbookRollbackResult,
    RunbookStep,
    RunbookSubmission,
    RunbookVerification,
)
from mth.core.runbooks.catalog import (
    DEFAULT_RUNBOOK_REGISTRY,
    AdminServicesDefinition,
    LanBridgeDefinition,
    RunbookRegistry,
    WanNatDefinition,
    WanPppoeDefinition,
)
from mth.core.runbooks.extended import (
    AddressListEntryDefinition,
    DhcpServerDefinition,
    DnsResolverDefinition,
    IpAddressDefinition,
    WireGuardPeerDefinition,
)
from mth.core.runbooks.history import (
    RunbookExecutionRecord,
    RunbookHistoryPaths,
    RunbookHistoryStore,
)
from mth.core.runbooks.typed import (
    APPROVED_TYPED_CHANGE_DOMAINS,
    TypedChangeDefinition,
    is_approval_bound_change,
    is_approved_typed_change,
    typed_definition_for_proposal,
    typed_proposals_for_domains,
)

__all__ = [
    "DEFAULT_RUNBOOK_REGISTRY",
    "AdminServicesDefinition",
    "APPROVED_TYPED_CHANGE_DOMAINS",
    "AddressListEntryDefinition",
    "DhcpServerDefinition",
    "DnsResolverDefinition",
    "LanBridgeDefinition",
    "IpAddressDefinition",
    "RunbookApplyResult",
    "RunbookBackend",
    "RunbookDefinition",
    "RunbookError",
    "RunbookExecutionRecord",
    "RunbookExecutor",
    "RunbookField",
    "RunbookFieldKind",
    "RunbookHistoryPaths",
    "RunbookHistoryStore",
    "RunbookPlan",
    "RunbookRegistry",
    "RunbookRollbackPreview",
    "RunbookRollbackResult",
    "RunbookStep",
    "RunbookSubmission",
    "RunbookVerification",
    "TypedChangeDefinition",
    "WanNatDefinition",
    "WanPppoeDefinition",
    "WireGuardPeerDefinition",
    "is_approved_typed_change",
    "is_approval_bound_change",
    "typed_definition_for_proposal",
    "typed_proposals_for_domains",
]
